#Program 1 of Tathastu-Week of Code by shaswat-99
n1=input("Enter your name")
n2=input("Enter your Branch")
n3=input("Enter your Gender")
n4=input("Enter your College name")
n5=int(input("Enter your Age"))
print("Name = ",n1)
print("Branch = ",n2)
print("Gender = ",n3)
print("College = ",n4)
print("Age = ",n5)
